name: Publish XCFramework

on:
  push:
    branches: [main]
    paths:
      - 'version.txt'

jobs:
  build-and-publish:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read Version
        id: read-version
        run: |
          VERSION=$(cat version.txt)
          echo "TAG=v${VERSION}" >> $GITHUB_ENV

      - name: Generate XCFramework
        run: ./gradlew :shared:assembleSharedXCFramework

      - name: Zip XCFramework
        run: zip -r Shared.xcframework.zip shared/build/XCFrameworks/release/Shared.xcframework

      - name: Compute Checksum
        id: checksum
        run: |
          CHECKSUM=$(swift package compute-checksum Shared.xcframework.zip)
          echo "CHECKSUM=$CHECKSUM" >> $GITHUB_ENV

      - name: Create and Push Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag ${{ env.TAG }}
          git push origin ${{ env.TAG }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ env.TAG }}
          name: "Release ${{ env.TAG }}"
          body: "Release ${{ env.TAG }} of Shared XCFramework"
          files: Shared.xcframework.zip

      - name: Update Swift Package Repo
        env:
          SWIFT_PACKAGE_REPO_TOKEN: ${{ secrets.SWIFT_PACKAGE_REPO_TOKEN }}
        run: |
          git clone https://x-access-token:$SWIFT_PACKAGE_REPO_TOKEN@github.com/duduaiqfome/swift-package.git
          cd swift-package
          sed -i '' "s|url: \".*\", from: \".*\"|url: \"$KMP_REPO_URL\", from: \"${{ env.TAG }}\"|g" Package.swift
          sed -i '' "s|checksum: \".*\"|checksum: \"${{ env.CHECKSUM }}\"|g" Package.swift
          git add Package.swift
          git commit -m "Update to ${{ env.TAG }}"
          git push origin main
          git tag ${{ env.TAG }} || true
          git push origin ${{ env.TAG }}
