name: Publish XCFramework

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Generate XCFramework
        run: ./gradlew :shared:assembleSharedXCFramework
      
      - name: Zip XCFramework
        run: zip -r Shared.xcframework.zip shared/build/XCFrameworks/release/Shared.xcframework
      
      - name: Get Release Tag
        id: get-tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      
      - name: Compute Checksum
        id: checksum
        run: |
          CHECKSUM=$(swift package compute-checksum Shared.xcframework.zip)
          echo "CHECKSUM=$CHECKSUM" >> $GITHUB_ENV
      
      - name: Update Swift Package Repo
        env:
          SWIFT_PACKAGE_REPO_TOKEN: ${{ secrets.SWIFT_PACKAGE_REPO_TOKEN }}
        run: |
          git clone git@github.com:duduaiqfome/appKmp.git
          cd swift-package
          sed -i '' "s|download/\(v[0-9.]\+\)/Shared.xcframework.zip|download/${{ env.TAG }}/Shared.xcframework.zip|g" Package.swift
          sed -i '' "s|checksum: \".*\"|checksum: \"${{ env.CHECKSUM }}\"|g" Package.swift
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Package.swift
          git commit -m "Update to ${{ env.TAG }}"
          git tag ${{ env.TAG }}
          git push origin main --tags
