name: Publish XCFramework

on:
  push:
    tags:
      - 'v*'  # Trigger the workflow on tag pushes

jobs:
  build-and-publish:
    runs-on: macos-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate XCFramework
        run: ./gradlew :shared:assembleSharedXCFramework
      
      - name: Zip XCFramework
        run: zip -r Shared.xcframework.zip shared/build/XCFrameworks/release/Shared.xcframework
      
      - name: Extract Tag Name
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      
      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ env.RELEASE_TAG }}
          files: Shared.xcframework.zip
